### PR TITLE
ISSUE 9 initial solution //airon

### PR DESCRIPTION
**Pull request by AironDev**
**Before submitting your PR for review**

- Run `npm run lint` to find errors in code syntax/format
- Run `npm run lint:fix` to fix all auto-fixable errors in source code and auto-format with prettier
- Ensure you fix any linting errors displayed after running any of the above commands

**ISSUE #9?**
[FEATURE REQUEST] GET ALL COMMENTS ON A REPORT (INCLUDING FLAGGED COMMENTS) 
I created a single configurable  route to get 
- all comments, 
- flagged comments
- unflagged comments

**HOW TO TEST**
- Flagged comments can be retrieved by passing an origin  and flagged key as query params eg. /comments/?origin=123123&flagged  OR   /comments/?origin=123123&flagged=true
- Unflagged comments can be retrieved by passing an origin and unflagged key as query params  eg. /comments/?origin=123123&unflagged OR  /comments/?origin=123123&unflagged=true
-  all comments can be retrieved by simply passing an origin key as query params  eg. /comments/?origin=123123

**LINK TO GITHUB ISSUE**
[Issue #9](https://github.com/microapidev/comment-microapi/issues/9)

**Questions:**
My current solution is based on the existing model structure, kindly notify me if any adjustment is required on this issue.
Thanks

**SLACK DETAILS**
- username: @airon
- email: airondev@gmail.com
- full-name: Aaron, Aniebiet B.

### CODE REVIEW

**Comment by oscar-ekeyekwu** [comment]
please refactor and update PR to match the doc..
isFlagged should be true or false and not flagged or unflagged

**Comment by oscar-ekeyekwu** [comment]
Also Factor in the refId which is the id of the comment service user. the origin is the origin of the comment from that ref

**Comment by AironDev** [comment]
This is what is in the docs:
comments/refs/{refId}

How I understand it is that,
refs and refId should be  url parameters then origin and isFlagged can come in as query strings.
Eg. comments/expenseng/reports/
Eg. comments/expenseng/reports/?origi n=123123&isFlagged=false

Please clarify this for me
Thanks

**Comment by oscar-ekeyekwu** [comment]
You know that in expenseng, there are several reports and possibly pages, right? Expenditure, Ministries and Companies Reports and some pages can be the origin. so the refId will be provided by the api consumers for us to store and will be used by then to retrieve their comment. 

just know this while you work ..

The supposed url should look like this 
comments/ref/{refId}

**Comment by AironDev** [comment]
Ok - I get it, Thanks
Meanwhile looking at the comments model, refs is not defined. Also dummy data in db does not have refs

**Pull request closed without merging**
